spring:
  application:
    name: first_microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/first_microservice
    username: {POSTGRES_USERNAME}
    password: {POSTGRES_PASSWORD}
    driver-class: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        format_sql: true
    database: postgresql
some:
  data:
    for:
      check: you_are_in_first_microservice